#
# Travis CI recipe to build docker image.
#

sudo: required

language: generic

services:
  - docker

script:
  - |
    if [[ "$TRAVIS_EVENT_TYPE" = "cron" ]]; then
      travis_wait 60 sh .travis.nightly
    else
      echo "Starting build of Docker image..."
      docker build \
        --no-cache \
        --pull \
        -t $TRAVIS_REPO_SLUG:$TRAVIS_JOB_ID .
    fi
